#!/bin/bash

 ##############################################################################
 #                                                                            #
 # Copyright 2022 MachineWare GmbH                                            #
 # All Rights Reserved                                                        #
 #                                                                            #
 # This is unpublished proprietary work and may not be used or disclosed to   #
 # third parties, copied or duplicated in any form, in whole or in part,      #
 # without prior written permission of the authors.                           #
 #                                                                            #
 ##############################################################################

home="$(cd $(dirname $(dirname ${BASH_SOURCE[0]} )) &>/dev/null && pwd)"
formatter="$home/cmake/Tools/$(uname -s)/clang-format-15.$(arch)"
srcdirs="$home/src $home/include $home/test"
sources=$(find $srcdirs -name '*.h' -or -name '*.cpp' | grep -v googletest)
exec $formatter --Werror $sources $@
