#!/bin/bash -e

 ##############################################################################
 #                                                                            #
 # Copyright 2022 MachineWare GmbH                                            #
 # All Rights Reserved                                                        #
 #                                                                            #
 # This is unpublished proprietary work and may not be used or disclosed to   #
 # third parties, copied or duplicated in any form, in whole or in part,      #
 # without prior written permission of the authors.                           #
 #                                                                            #
 ##############################################################################

home="$(cd $(dirname $(dirname ${BASH_SOURCE[0]})) &>/dev/null && pwd)"
linter="$(which clang-tidy);--extra-arg=-std=c++17"
builds=$@

[ -z "$builds" ] && builds="DEBUG RELEASE ASAN"

for type in $builds; do (
    prefix=$home/BUILD/$type
    build=$prefix/.BUILD

    cmake -B $build -G Ninja                 \
          -DCMAKE_BUILD_TYPE=$type           \
          -DCMAKE_INSTALL_PREFIX=$prefix     \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DMWR_BUILD_TESTS=ON               \
          -DMWR_LINTER=$linter               \
          $home

    cmake --build $build -j $(nproc) -- install
) done
