name: asan

on:
  push:
    branches:
      - 'main'
      - 'dev**'

env:
  TARGET_ARCH: linux64
  ASAN_OPTIONS: verbosity=1
  TSAN_OPTIONS: verbosity=1
  UBSAN_OPTIONS: print_stacktrace=1

jobs:
  sanitize:
    name: ${{matrix.sanitizer}}
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        sanitizer: [ASAN, TSAN, UBSAN]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install libelf-dev ninja-build

    - name: Configure
      run: cmake -G Ninja -B BUILD -DCMAKE_BUILD_TYPE=${{matrix.sanitizer}} -DMWR_BUILD_TESTS=ON

    - name: Build
      run: cmake --build BUILD

    - name: Test
      working-directory: BUILD
      run: ctest --verbose

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: '!cancelled()'
      with:
        name: ${{github.event.repository.name}}-logs-${{matrix.sanitizer}}
        path: |
            BUILD/.ninja_log
            BUILD/CMakeCache.txt
            BUILD/Testing/Temporary/LastTest.log
        include-hidden-files: true
        retention-days: 7
