name: coverage

on:
  push:
    branches:
      - 'main'
      - 'dev**'

env:
  BUILD_TYPE: DEBUG

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install libelf-dev ninja-build gcovr

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DMWR_BUILD_TESTS=ON -DMWR_COVERAGE=ON

    - name: Build Project
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j $(nproc)

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

    - name: Generate Coverage Report
      run: |
        mkdir -p mwr-coverage-report
        gcovr --html-details -f 'include/*' -f 'src/*' --output mwr-coverage-report/mwr.html --exclude-lines-by-pattern '\s*MWR_ERROR.*'

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        retention-days: 3
        name: mwr-coverage-report
        path: mwr-coverage-report/

