name: cross

on:
  push:
    branches:
      - 'main'
      - 'dev**'
  pull_request:
    branches:
      - 'main'

env:
  BUILD_TYPE: Release

jobs:
  crossbuild:
    name: crossbuild
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [self-hosted-ubuntu-22.04-arm64]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DMWR_BUILD_TESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j $(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

