name: mingw

on:
  push:
    branches:
      - 'main'
      - 'dev**'

env:
  BUILD_TYPE: RelWithDebInfo

defaults:
  run:
    shell: msys2 {0}

jobs:
  mingw:
    name: mingw
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2025]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup dependencies
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: mingw64
        pacboy: cc:p cmake:p ninja:p

    - name: Configure
      run: cmake -G Ninja -B BUILD -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DMWR_BUILD_TESTS=ON

    - name: Build
      run: cmake --build BUILD

    - name: Test
      working-directory: BUILD
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: '!cancelled()'
      with:
        name: ${{github.event.repository.name}}-logs-${{matrix.os}}-mingw
        path: |
            BUILD/.ninja_log
            BUILD/CMakeCache.txt
            BUILD/msbuild.binlog
            BUILD/Testing/Temporary/LastTest.log
        include-hidden-files: true
        retention-days: 7
