name: msvc

on:
  push:
    branches:
      - 'main'
      - 'dev**'

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  msvc:
    name: msvc
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2025]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Configure
      run: cmake -B BUILD -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DMWR_BUILD_TESTS=ON

    - name: Build
      run: cmake --build BUILD --config ${{env.BUILD_TYPE}} -- /bl

    - name: Test
      working-directory: BUILD
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: '!cancelled()'
      with:
        name: ${{github.event.repository.name}}-logs-${{matrix.os}}-msvc
        path: |
            BUILD/.ninja_log
            BUILD/CMakeCache.txt
            BUILD/msbuild.binlog
            BUILD/Testing/Temporary/LastTest.log
        include-hidden-files: true
        retention-days: 7
