name: nightly

on:
  schedule:
    - cron: '0 20 * * *'

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  nightly:
    name: nightly
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm, self-hosted-rhel-8, windows-2022, windows-2025, macos-13, macos-14]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Dependencies
      if: contains(matrix.os, 'self-hosted') == false && contains(matrix.os, 'ubuntu') == true
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install libelf-dev ninja-build

    - name: Configure
      if: runner.os != 'Windows'
      run: cmake -G Ninja -B BUILD -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DMWR_BUILD_TESTS=ON

    - name: Configure (Windows)
      if: runner.os == 'Windows'
      run: cmake -B BUILD -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DMWR_BUILD_TESTS=ON

    - name: Build
      if: runner.os != 'Windows'
      run: cmake --build BUILD

    - name: Build (Windows)
      if: runner.os == 'Windows'
      run: cmake --build BUILD --config ${{env.BUILD_TYPE}} -- /bl

    - name: Test
      working-directory: BUILD
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: '!cancelled()'
      with:
        name: ${{github.event.repository.name}}-logs-${{matrix.os}}
        path: |
            BUILD/.ninja_log
            BUILD/CMakeCache.txt
            BUILD/msbuild.binlog
            BUILD/Testing/Temporary/LastTest.log
        include-hidden-files: true
        retention-days: 7
