name: nightly

on:
  schedule:
    - cron: '0 1 * * *'

env:
  BUILD_TYPE: Release

jobs:
  nightly:
    name: nightly
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, self-hosted-ubuntu-22.04-arm64, windows-2019]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup Dependencies
      run: sudo apt-get install libelf-dev ninja-build
      if: contains(matrix.os, 'self-hosted') == false && contains(matrix.os, 'windows') == false

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DMWR_BUILD_TESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j $(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

