name: style

on:
  push:
    branches:
      - 'main'
      - 'dev**'
  pull_request:
    branches: [ main ]

jobs:
  style:
    name: style
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        token: ${{ secrets.CI_TOKEN }}

    - name: Check Format
      run: ./utils/format -n

